server:
  port: 8082

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
      #  bootstrap-servers: localhost:9092
        output:
          destination: persistenceServiceTopic
          content-type: application/json
      kafka:
        binder:
          headers:
          brokers: localhost
          #defaultBrokerPort: 9092
          zkNodes: localhost

