eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8901
  servlet:
    context-path: /auth

spring:
  datasource:
    driver-class-name: ${PSQLDBDRIVER}
    url: ${PSQLDBURL}
    username: ${PSQLDBUSER}
    password: ${PSQLDBPASS}

# TODO - change this, encrypt it and put it in Config server
signing:
  key: "345345fsdfsf5345"
