INSERT INTO public.book (book_id, title, testament) VALUES (1, 'Genesis', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (2, 'Exodus', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (3, 'Leviticus', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (4, 'Numbers', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (5, 'Deuteronomy', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (6, 'Joshua', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (7, 'Judges', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (8, 'Ruth', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (9, '1 Samuel', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (10, '2 Samuel', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (11, '1 Kings', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (12, '2 Kings', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (13, '1 Chronicles', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (14, '2 Chronicles', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (15, 'Ezra', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (16, 'Nehemiah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (17, 'Esther', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (18, 'Job', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (19, 'Psalms', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (20, 'Proverbs', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (21, 'Ecclesiastes', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (22, 'The Song of Solomon', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (23, 'Isaiah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (24, 'Jeremiah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (25, 'Lamentations', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (26, 'Ezekiel', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (27, 'Daniel', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (28, 'Hosea', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (29, 'Joel', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (30, 'Amos', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (31, 'Obadiah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (32, 'Jonah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (33, 'Micah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (34, 'Nahum', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (35, 'Habakkuk', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (36, 'Zephaniah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (37, 'Haggai', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (38, 'Zechariah', 'OT');
INSERT INTO public.book (book_id, title, testament) VALUES (39, 'Malachi', 'OT');
