INSERT INTO public.books (book_id, title, testament) VALUES (1, 'Genesis', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (2, 'Exodus', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (3, 'Leviticus', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (4, 'Numbers', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (5, 'Deuteronomy', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (6, 'Joshua', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (7, 'Judges', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (8, 'Ruth', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (9, '1 Samuel', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (10, '2 Samuel', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (11, '1 Kings', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (12, '2 Kings', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (13, '1 Chronicles', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (14, '2 Chronicles', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (15, 'Ezra', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (16, 'Nehemiah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (17, 'Esther', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (18, 'Job', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (19, 'Psalms', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (20, 'Proverbs', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (21, 'Ecclesiastes', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (22, 'The Song of Solomon', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (23, 'Isaiah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (24, 'Jeremiah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (25, 'Lamentations', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (26, 'Ezekiel', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (27, 'Daniel', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (28, 'Hosea', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (29, 'Joel', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (30, 'Amos', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (31, 'Obadiah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (32, 'Jonah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (33, 'Micah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (34, 'Nahum', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (35, 'Habakkuk', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (36, 'Zephaniah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (37, 'Haggai', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (38, 'Zechariah', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (39, 'Malachi', 'OT');
INSERT INTO public.books (book_id, title, testament) VALUES (40, 'Matthew', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (41, 'Mark', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (42, 'Luke', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (43, 'John', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (44, 'Acts', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (45, 'Romans', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (46, '1 Corinthians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (47, '2 Corinthians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (48, 'Galatians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (49, 'Ephesians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (50, 'Philippians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (51, 'Colossians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (52, '1 Thessalonians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (53, '2 Thessalonians', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (54, '1 Timothy', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (55, '2 Timothy', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (56, 'Titus', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (57, 'Philemon', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (58, 'Hebrews', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (59, 'James', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (60, '1 Peter', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (61, '2 Peter', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (62, '1 John', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (63, '2 John', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (64, '3 John', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (65, 'Jude', 'NT');
INSERT INTO public.books (book_id, title, testament) VALUES (66, 'Revelation', 'NT');
