server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mikeyjay39/mybiblestudywebapp-config
          searchPaths: mybiblestudyservice
          username: mikeyjay39
          password: M$6%uqKv*g8K #TODO change this
#TODO remove this when config server is set up
management:
  security:
    enabled: false


