spring:
  datasource:
    driver-class-name: ${PSQLDBDRIVER}
    url: ${PSQLDBURL}
    username: ${PSQLDBUSER}
    password: ${PSQLDBPASS}
  main.allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
  data:
    repositories:
      enabled: true
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

hystrix:
  shareSecurityContext: true

redis:
  server: "localhost"
  port: "6379"