spring:
  datasource:
    driver-class-name: ${PSQLDBDRIVER}
    url: ${PSQLDBURL}
    username: ${PSQLDBUSER}
    password: ${PSQLDBPASS}
  main.allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

hystrix:
  shareSecurityContext: true

security:
  oauth2:
    server:
      token-endpoint: http://localhost:8901/auth/oauth/token
    client:
      client-id: mybiblestudywebapp
      client-secret: secret
      scope: openid email params groups webclient mobileclient
    resource:
      token-info-uri: http://localhost:8901/auth/oauth/check_token
      userInfoUri: http://localhost:8901/auth/user

# TODO: change, encrypt, remove and put in Spring cloud config global
signing:
  key: "345345fsdfsf5345"