spring:
  datasource:
    driver-class-name: ${PSQLDBDRIVER}
    url: ${PSQLDBURL}
    username: ${PSQLDBUSER}
    password: ${PSQLDBPASS}
  main.allow-bean-definition-overriding: true
  redis:
    host: ${REDISSERVER_URI}
    port: 6379
  cloud:
    #config:
    #  uri: http://localhost:8888
    stream:
      bindings:
        #bootstrap-servers: zookeeper:2181
        input:
          destination: persistenceServiceTopic
          content-type: application/json
          group: mystudybibleGroup
      kafka:
        binder:
          brokers: ${KAFKASERVER_URI}
          zkNodes: ${ZKSERVER_URI}
  data:
    repositories:
      enabled: true
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI}

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

hystrix:
  shareSecurityContext: true

redis:
  #server: "localhost"
  port: "6379"